### ISSUE TITLE
你好，能不能说一下具体怎么使用呢？刚刚接触CFDEM，还不清楚怎么使用修改过的求解器😃。

### ISSUE THREAD

**Issue by 3ys** [sjtuWangDing/MSP-CFDEMcoupling#3]

**Comment by sjtuWangDing** [comment]
直接在 src 目录下编译出动态库，然后在对应的求解器目录下编译求解器就可以了

**Comment by 3ys** [comment]
能不能加个联系方式呢，有偿向您请教学习一下，弄了好久还是一直报错😓



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2023年9月20日(周三) 中午1:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sjtuWangDing/MSP-CFDEMcoupling] 你好，能不能说一下具体怎么使用呢？刚刚接触CFDEM，还不清楚怎么使用修改过的求解器😃。 (Issue #3)




 
直接在 src 目录下编译出动态库，然后在对应的求解器目录下编译求解器就可以了

**Comment by hugaoyang** [comment]
@3ys 请问您现在是怎么编译成功的呢，可以请教一下吗

**Comment by hugaoyang** [comment]
你好呀，&nbsp; &nbsp; &nbsp;我现在已经解决了安装的问题，我发现是因为我安装前没有加载环境变量导致的
感谢你的回复
&nbsp;


枫帝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月9日(星期六) 晚上9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sjtuWangDing/MSP-CFDEMcoupling] 你好，能不能说一下具体怎么使用呢？刚刚接触CFDEM，还不清楚怎么使用修改过的求解器😃。 (Issue #3)





 
Closed #3 as completed.
