### ISSUE TITLE
使用semi求解器时，Construct implicitCouple model遇到错误

### ISSUE THREAD

**Issue by 3ys** [sjtuWangDing/MSP-CFDEMcoupling#4]
我在使用semi求解器计算自己修改过的算例时，遇到错误，下面是错误信息：
“Selecting momCoupleModel: implicitCouple
Construct implicitCouple model...
ERROR on proc 6: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)”
请问这个问题该怎么解决呢？

我把coupling文件设置放在下面：
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  1.4                                   |
|   \\  /    A nd           | Web:      http://www.openfoam.org               |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/

FoamFile
{
  version         2.0;
  format          ascii;
  root            "";
  case            "";
  instance        "";
  local           "";
  class           dictionary;
  object          couplingProperties;
}

/* ---------------------------- sub-models & settings ---------------------------- */

modelType Bfull; // A or B

couplingInterval 10;

expandedCellScale 4;

allowUseSubCFDTimeStep false;

globalForce mixGlobalForce;

useGuoBBOEquation false;

useDDtVoidFraction true;

forceModels
(
  Archimedes
  mixDragForce
  mixVirtualMassForce
  mixMeiLiftForce
  mixGradPForce // ++++++++++++
  mixViscForce  // ++++++++++++
);

momCoupleModels
(
  implicitCouple
);

voidFractionModel mix; // divided, centre, mix

locateModel engineMix; // engine, engineIB, engineMix

meshMotionModel noMeshMotion;

dataExchangeModel twoWayMPI;

averagingModel dense; // dense dilute

turbulenceModelType turbulenceProperties;

/* ---------------------------- sub-model properties ------------------------- */

implicitCoupleProps
{
  velFieldName "U";
  granVelFieldName "Us";
  voidFractionFieldName "voidFraction";
}

"(globalForceProps|mixGlobalForceProps)"
{
  verbose true;
  GaussCoreEff 3;
  velFieldName "U";
  voidFractionFieldName "voidFraction";
  gravityFieldName "g";
}

ArchimedesProps
{
  treatForceExplicitInMomEquation false;
  treatForceBothCFDAndDEM false; // 
  treatDEMForceImplicit false;
  verbose true;
  interpolation false;
  scalarViscosity false; //++++++
}

mixDragForceProps
{
  dragModelName "Gidaspow";
  treatForceExplicitInMomEquation false;
  treatForceBothCFDAndDEM true;
  treatDEMForceImplicit false;
  verbose true;
  interpolation false;
  scalarViscosity false;
  useGaussCoreFunctionRefined true;
}

mixMeiLiftForceProps
{
  useSecondOrderTerms false;
  treatForceBothCFDAndDEM true;
  verbose true;
  useGaussCoreFunctionRefined true;
}

mixVirtualMassForceProps
{
  treatForceBothCFDAndDEM true;
  verbose true;
  useGaussCoreFunctionRefined true;
}

/*++++++++++++++++++++++++++++++++++++*/
mixGradPForceProps
{
  treatForceExplicitInMomEquation true;
  treatForceBothCFDAndDEM true; // 
  treatDEMForceImplicit false;
  verbose true;
  useGaussCoreFunctionRefined true;
}

mixViscForceProps
{
  treatForceExplicitInMomEquation true;
  treatForceBothCFDAndDEM true; // 
  treatDEMForceImplicit false;
  verbose true;
  useGaussCoreFunctionRefined true;
}
/*++++++++++++++++++++++++++++++++++++*/

twoWayMPIProps
{
  liggghtsPath "../DEM/in.liggghts_run";
}

dividedProps
{
  alphaMin 0.3;
  scaleUpVol 1.0;
}

mixProps
{
  verbose true;
  alphaMin 0.3;
  scaleUpVol 1.0;
}

centreProps
{
  alphaMin 0.3;
}

bigParticleProps
{
  maxCellsPerParticle 1000;
  alphaMin 0.3;
  scaleUpVol 1.0;
}

engineProps
{
  treeSearch false;
}

engineMixProps
{
  verbose true;
  treeSearch true;
  zSplit 8;
  xySplit 16;
}

**Comment by 3ys** [comment]
重新看了下错误信息，发现有提到“number of particles: 0”。是不是颗粒必须事先就在流场中全部生成，不能边运行边生成颗粒呢？

“ERROR on proc 7: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 8: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 4: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 9: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 3: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 2: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 6: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 5: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
ERROR on proc 1: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)
number of particles: 0
ERROR on proc 0: Illegal length used in CfdDatacouplingMPI::allocate_external (../cfd_datacoupling_mpi.cpp:160)”

**Comment by sjtuWangDing** [comment]
崩在了 Liggghts 里了，可以查看下具体的源码，不清楚是不是最开始计算的时候还没有任何颗粒

**Comment by 3ys** [comment]
好的，谢谢哈，基本解决了



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2023年12月1日(周五) 晚上8:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sjtuWangDing/MSP-CFDEMcoupling] 使用semi求解器时，Construct implicitCouple model遇到错误 (Issue #4)




 
崩在了 Liggghts 里了，可以查看下具体的源码，不清楚是不是最开始计算的时候还没有任何颗粒
